name: 'Deque Accessibility Issue Labeler'
description: 'Labels issues automatically for accessibility based on their body'
author: 'Deque'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
runs:
  using: node16
  main: dist/index.js
branding:
  icon: 'activity'
  color: 'blue'
